{
  imports = [
    ./boot.nix
    ./desktop.nix
    ./flatpak.nix
    ./gaming.nix
    ./home.nix
    ./limits.nix
    ./locale.nix
    ./nix-settings.nix
    ./polkit.nix
    ./services.nix
    ./syncthing.nix
    ./theme.nix
    ./user.nix
    ./virt.nix
    ./zram.nix
  ];
}
